services:
    quizmaster:
        image: ghcr.io/scrumdojo/dev-quizmaster:v4
        hostname: quizmaster
        environment: 
            - SSH_START=true
        ports:
            - 2222:22
        volumes:
            - devhome:/home/dev

    postgres:
        image: postgres:16
        hostname: postgres
        environment:
            POSTGRES_USER: quizmaster
            POSTGRES_PASSWORD: quizmaster
            POSTGRES_DB: quizmaster
        volumes:
            - db:/var/lib/postgresql/data

volumes:
    devhome:
    db:
