spring.application.name=quizmaster
server.port=${BE_PORT:8080}

spring.datasource.url=jdbc:postgresql://${DB_HOST:postgres}:5432/${DB_NAME:quizmaster}
spring.datasource.username=${DB_USER:quizmaster}
spring.datasource.password=${DB_PASS:quizmaster}
spring.datasource.driver-class-name=org.postgresql.Driver

feature.flag=${FEATURE_FLAG:false}
ai.token=${OPENROUTER_API_KEY:}
ai.model=${OPENROUTER_MODEL:openai/gpt-4o-mini}
